Invalid:
- all:
   - changed-files:
     - any-glob-to-any-file: 'projects/**'
     - all-globs-to-any-file: 'projects/**'

Dev:
- all:
  - changed-files:
    - any-glob-to-any-file: '*'
    - all-globs-to-any-file: '!projects/**'

Submission:
 - changed-files:
   - any-glob-to-any-file: 'projects/**'
