<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /home/ryan/Desktop/PCB/OnBoard/showcase/static/pcb.gltf --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/pcb-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Shape_9.geometry} material={gltf.materials.APP_1} />
    <T.Mesh geometry={gltf.nodes.Shape_10.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_11.geometry} material={gltf.materials.APP_3} />
    <T.Mesh geometry={gltf.nodes.Shape_12.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_13.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_14.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_15.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_16.geometry} material={gltf.materials.APP_8} />
    <T.Mesh geometry={gltf.nodes.Shape_17.geometry} material={gltf.materials.APP_9} />
    <T.Mesh geometry={gltf.nodes.Shape_18.geometry} material={gltf.materials.APP_8} />
    <T.Mesh geometry={gltf.nodes.Shape_19.geometry} material={gltf.materials.APP_9} />
    <T.Mesh geometry={gltf.nodes.Shape_20.geometry} material={gltf.materials.APP_8} />
    <T.Mesh geometry={gltf.nodes.Shape_21.geometry} material={gltf.materials.APP_1} />
    <T.Mesh geometry={gltf.nodes.Shape_22.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_23.geometry} material={gltf.materials.APP_3} />
    <T.Mesh geometry={gltf.nodes.Shape_24.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_25.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_26.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_27.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_28.geometry} material={gltf.materials.APP_1} />
    <T.Mesh geometry={gltf.nodes.Shape_29.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_30.geometry} material={gltf.materials.APP_3} />
    <T.Mesh geometry={gltf.nodes.Shape_31.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_32.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_33.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_34.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_35.geometry} material={gltf.materials.APP_1} />
    <T.Mesh geometry={gltf.nodes.Shape_36.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_37.geometry} material={gltf.materials.APP_3} />
    <T.Mesh geometry={gltf.nodes.Shape_38.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_39.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_40.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_41.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_42.geometry} material={gltf.materials.APP_20} />
    <T.Mesh geometry={gltf.nodes.Shape_43.geometry} material={gltf.materials.APP_21} />
    <T.Mesh geometry={gltf.nodes.Shape_44.geometry} material={gltf.materials.APP_20} />
    <T.Mesh geometry={gltf.nodes.Shape_45.geometry} material={gltf.materials.APP_23} />
    <T.Mesh geometry={gltf.nodes.Shape_46.geometry} material={gltf.materials.APP_24} />
    <T.Mesh geometry={gltf.nodes.Shape_47.geometry} material={gltf.materials.APP_20} />
    <T.Mesh geometry={gltf.nodes.Shape_48.geometry} material={gltf.materials.APP_23} />
    <T.Mesh geometry={gltf.nodes.Shape_49.geometry} material={gltf.materials.APP_27} />
    <T.Mesh geometry={gltf.nodes.Shape_50.geometry} material={gltf.materials.APP_28} />
    <T.Mesh geometry={gltf.nodes.Shape_51.geometry} material={gltf.materials.APP_27} />
    <T.Mesh geometry={gltf.nodes.Shape_52.geometry} material={gltf.materials.APP_28} />
    <T.Mesh geometry={gltf.nodes.Shape_53.geometry} material={gltf.materials.APP_27} />
    <T.Mesh geometry={gltf.nodes.Shape_54.geometry} material={gltf.materials.APP_28} />
    <T.Mesh geometry={gltf.nodes.Shape_55.geometry} material={gltf.materials.APP_27} />
    <T.Mesh geometry={gltf.nodes.Shape_56.geometry} material={gltf.materials.APP_21} />
    <T.Mesh geometry={gltf.nodes.Shape_57.geometry} material={gltf.materials.APP_27} />
    <T.Mesh geometry={gltf.nodes.Shape_58.geometry} material={gltf.materials.APP_21} />
    <T.Mesh geometry={gltf.nodes.Shape_59.geometry} material={gltf.materials.APP_28} />
    <T.Mesh geometry={gltf.nodes.Shape_60.geometry} material={gltf.materials.APP_1} />
    <T.Mesh geometry={gltf.nodes.Shape_61.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_62.geometry} material={gltf.materials.APP_3} />
    <T.Mesh geometry={gltf.nodes.Shape_63.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_64.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape_65.geometry} material={gltf.materials.APP_2} />
    <T.Mesh geometry={gltf.nodes.Shape_66.geometry} material={gltf.materials.APP_5} />
    <T.Mesh geometry={gltf.nodes.Shape.geometry} material={gltf.materials.APP_45} />
    <T.Mesh geometry={gltf.nodes.Shape_1.geometry} material={gltf.materials.APP_45} />
    <T.Mesh geometry={gltf.nodes.Shape_2.geometry} material={gltf.materials.APP_46} />
    <T.Mesh geometry={gltf.nodes.Shape_3.geometry} material={gltf.materials.APP_47} />
    <T.Mesh geometry={gltf.nodes.Shape_4.geometry} material={gltf.materials.APP_48} />
    <T.Mesh geometry={gltf.nodes.Shape_5.geometry} material={gltf.materials.APP_46} />
    <T.Mesh geometry={gltf.nodes.Shape_6.geometry} material={gltf.materials.APP_49} />
    <T.Mesh geometry={gltf.nodes.Shape_7.geometry} material={gltf.materials.APP_50} />
    <T.Mesh geometry={gltf.nodes.Shape_8.geometry} material={gltf.materials.APP_50} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
